id: I575BB5AE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:15:40+00:00'
last_modified: '2022-06-10T09:28:57.402950+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27597
  title: ཨོ་རྒྱན་གུ་རུ་པདྨ་འབྱུང་གནས་ཀྱི་རྣམ་ཐར་བསྡུས་པ་དོན་ལྡན་དང་འབྲེལ་བའི་སྙིང་པོ་རྡོ་རྗེའི་སྒྲ་དབྱངས་ཀྱི་ཕྲེང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E8E5:
      image_group_id: I4505
      title: ''
      total_pages: 112
      order: 1
      base_file: E8E5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
