id: P000551
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W27597
  title: ཨོ་རྒྱན་གུ་རུ་པདྨ་འབྱུང་གནས་ཀྱི་རྣམ་ཐར་བསྡུས་པ་དོན་ལྡན་དང་འབྲེལ་བའི་སྙིང་པོ་རྡོ་རྗེའི་སྒྲ་དབྱངས་ཀྱི་ཕྲེང་བ
  author: ''
  volumes:
    58adbe21f7e24ac38c3eb88fefb41966:
      image_group_id: I4505
      title: ''
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
