id: opecha:P000551
initial_creation_type: ocr
source_metadata:
  id: bdr:W27597
  title: ཨོ་རྒྱན་གུ་རུ་པདྨ་འབྱུང་གནས་ཀྱི་རྣམ་ཐར་བསྡུས་པ་དོན་ལྡན་དང་འབྲེལ་བའི་སྙིང་པོ་རྡོ་རྗེའི་སྒྲ་དབྱངས་ཀྱི་ཕྲེང་བ
  volume:
    58adbe21f7e24ac38c3eb88fefb41966:
      image_group_id: I4505
      title: ''
      volume_number: 1
      total_pages: 112
  author: ''
ebook_metadata:
  title: ཨོ་རྒྱན་གུ་རུ་པདྨ་འབྱུང་གནས་ཀྱི་རྣམ་ཐར་བསྡུས་པ་དོན་ལྡན་དང་འབྲེལ་བའི་སྙིང་པོ་རྡོ་རྗེའི་སྒྲ་དབྱངས་ཀྱི་ཕྲེང་བ
  author: ''
  sku: P000551
  cover: cover.jpg
  layers:
  - pagination
